"""LLM-backed explanation and remediation helper for rules engine findings.

This module is import-safe and designed to be fully mockable in tests.

Resolution order:
  1. OpenAI API (if OPENAI_API_KEY is set)
  2. Local Ollama LLM (if server is reachable)
  3. Deterministic template fallback (always available)
"""
from __future__ import annotations

import json
import logging
import re
from typing import Any, Dict, Optional
import os

logger = logging.getLogger(__name__)


def _call_llm(prompt: str, *, api_key: str) -> Dict[str, Any]:
    """Internal helper to call an LLM provider (OpenAI-compatible).

    This is deliberately simple and easy to mock in tests. To avoid
    introducing a hard dependency on the OpenAI SDK, we implement a
    minimal HTTP client only when an API key is present. In most
    environments, tests will patch this function directly.
    """

    import json
    import urllib.request

    # Use a generic OpenAI-compatible endpoint; can be overridden via env.
    base_url = os.getenv("OPENAI_API_BASE", "https://api.openai.com/v1")
    model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

    url = f"{base_url.rstrip('/')}/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    body = {
        "model": model,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are a cloud security expert explaining IaC misconfigurations "
                    "and concise remediations for DevSecOps engineers."
                ),
            },
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.2,
    }

    req = urllib.request.Request(url, data=json.dumps(body).encode("utf-8"), headers=headers)
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read().decode("utf-8"))

    message = (
        data.get("choices", [{}])[0]
        .get("message", {})
        .get("content", "")
        .strip()
    )

    return {"raw": data, "message": message}


def _deterministic_fallback(finding: Dict[str, Any], file_content: str) -> Dict[str, Any]:
    """Generate a deterministic explanation/remediation without external calls.

    This path is used when no API key is configured. It must be
    completely deterministic for testability.
    """

    rule_id = finding.get("rule_id") or finding.get("id") or "UNKNOWN_RULE"
    description = finding.get("description") or "Potential infrastructure-as-code risk detected."
    severity = finding.get("severity") or finding.get("level") or "UNKNOWN"
    file_path = finding.get("file_path") or finding.get("path") or "<unknown>"

    explanation = (
        f"Rule {rule_id} flagged this IaC resource as {severity}. "
        f"Description: {description}. "
        f"Location: {file_path}. "
        "This finding was generated by static analysis of the IaC file."
    )

    remediation = (
        "Review the flagged configuration and align it with your organization's "
        "cloud security best practices (for example, CIS Benchmarks or vendor "
        "hardening guides). Apply the least-privilege principle, avoid broad "
        "network exposure, and remove hard-coded secrets from the template."
    )

    # Fallback uses a medium certainty to indicate heuristic reasoning.
    return {
        "explanation": explanation,
        "remediation": remediation,
        "certainty": 0.6,
    }


def explain_and_remediate(finding: Dict[str, Any], file_content: str) -> Dict[str, Any]:
    """Return an LLM-backed or deterministic explanation/remediation for a finding.

    The return value is always a dict of the shape::

        {
          "explanation": str,
          "impact": str,        # optional — only present with a real LLM
          "remediation": str,
          "certainty": float,   # between 0.0 and 1.0
        }

    Resolution order:
      1. OpenAI API  (OPENAI_API_KEY set)
      2. Local Ollama (server reachable)
      3. Deterministic template fallback
    """

    # --- Path 1: OpenAI API ---
    api_key = os.getenv("OPENAI_API_KEY")
    if api_key:
        return _call_openai_path(finding, file_content, api_key)

    # --- Path 2: Local Ollama LLM ---
    try:
        from llm.local_llm_client import is_ollama_available, call_local_llm
        if is_ollama_available():
            result = _call_local_llm_path(finding, file_content, call_local_llm)
            if result is not None:
                return result
            logger.warning("Local LLM returned no usable output; falling back to deterministic")
    except ImportError:
        logger.debug("llm.local_llm_client not available; skipping local LLM path")
    except Exception as exc:
        logger.warning("Local LLM path failed: %s; falling back to deterministic", exc)

    # --- Path 3: Deterministic fallback ---
    return _deterministic_fallback(finding, file_content)


def _build_structured_prompt(finding: Dict[str, Any], file_content: str) -> str:
    """Build a concise prompt optimized for fast local LLM inference."""
    rule_id = finding.get("rule_id") or finding.get("id") or "UNKNOWN_RULE"
    description = finding.get("description") or "Potential IaC misconfiguration."
    severity = finding.get("severity") or finding.get("level") or "UNKNOWN"
    code_snippet = finding.get("code_snippet") or ""

    # Keep code context short to reduce inference time on CPU
    code_block = code_snippet if code_snippet else file_content[:1500]

    prompt = (
        f"IaC finding {rule_id} [{severity}]: {description[:200]}\n"
        f"Code:\n{code_block}\n\n"
        'Return JSON: {"explanation":"why dangerous","impact":"consequences","remediation":"fix steps","risk_level":"HIGH"}'
    )
    return prompt


_SYSTEM_MSG = "You are a cloud security expert. Respond with valid JSON only."


def _parse_structured_response(text: str) -> Optional[Dict[str, Any]]:
    """Parse structured JSON from an LLM response.

    Handles common issues: markdown fences, trailing text, etc.
    Returns None if parsing fails.
    """
    # Strip markdown code fences if present
    cleaned = re.sub(r'^```(?:json)?\s*', '', text.strip(), flags=re.MULTILINE)
    cleaned = re.sub(r'```\s*$', '', cleaned.strip(), flags=re.MULTILINE)

    try:
        data = json.loads(cleaned)
        if isinstance(data, dict) and "explanation" in data:
            return data
    except (json.JSONDecodeError, ValueError):
        pass

    # Try to extract JSON object from within other text
    match = re.search(r'\{.*"explanation".*\}', text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group())
        except (json.JSONDecodeError, ValueError):
            pass
    return None


def _certainty_from_risk(risk_level: str) -> float:
    """Map a risk_level string to a certainty value."""
    return {"CRITICAL": 0.95, "HIGH": 0.85, "MEDIUM": 0.7, "LOW": 0.55}.get(
        risk_level.upper(), 0.7
    )


def _call_local_llm_path(
    finding: Dict[str, Any], file_content: str, call_fn
) -> Optional[Dict[str, Any]]:
    """Try to get an explanation from the local Ollama LLM."""
    prompt = _build_structured_prompt(finding, file_content)
    raw = call_fn(prompt, system=_SYSTEM_MSG)
    if not raw:
        return None

    structured = _parse_structured_response(raw)
    if structured:
        risk = structured.get("risk_level", "MEDIUM")
        # Coerce list values to strings (0.6b models sometimes return arrays)
        remediation = structured.get("remediation", "")
        if isinstance(remediation, list):
            remediation = "\n".join(str(r) for r in remediation)
        impact = structured.get("impact", "")
        if isinstance(impact, list):
            impact = " ".join(str(i) for i in impact)
        return {
            "explanation": str(structured["explanation"]),
            "impact": str(impact),
            "remediation": str(remediation),
            "certainty": _certainty_from_risk(risk),
        }

    # Fallback: use raw text as explanation
    logger.info("Local LLM response was not valid JSON; using raw text")
    return {
        "explanation": raw,
        "impact": "",
        "remediation": "",
        "certainty": 0.65,
    }


def _call_openai_path(
    finding: Dict[str, Any], file_content: str, api_key: str
) -> Dict[str, Any]:
    """Original OpenAI-based explanation path."""
    prompt = _build_structured_prompt(finding, file_content)

    try:
        resp = _call_llm(prompt, api_key=api_key)
        message = str(resp.get("message", "")).strip()
        if not message:
            raise ValueError("Empty LLM response")

        structured = _parse_structured_response(message)
        if structured:
            risk = structured.get("risk_level", "MEDIUM")
            return {
                "explanation": structured["explanation"],
                "impact": structured.get("impact", ""),
                "remediation": structured.get("remediation", ""),
                "certainty": _certainty_from_risk(risk),
            }

        # Legacy unstructured fallback
        certainty: float = 0.8
        lower = message.lower()
        marker = "certainty:"
        if marker in lower:
            idx = lower.rfind(marker)
            tail = lower[idx + len(marker) :].strip()
            token = tail.split()[0]
            try:
                parsed = float(token)
                if 0.0 <= parsed <= 1.0:
                    certainty = parsed
            except ValueError:
                pass

        return {
            "explanation": message,
            "remediation": "See the recommended remediation steps described above.",
            "certainty": certainty,
        }
    except Exception:
        return _deterministic_fallback(finding, file_content)
